<a href="https://colab.research.google.com/github/DataMastersUN/FA_T3/blob/main/Trabajo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pickle
import cv2
import os
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import math

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
from PIL import Image
from IPython.display import display

#imagen = Image.open('/content/drive/Shareddrives/FdeAnaliticaG4/Proyecto3/an2i_left_happy_sunglasses_2.pgm')

#display(imagen3)



In [29]:
#ancho, alto = imagen.size
#print(f"Tamaño de la imagen: {ancho}x{alto}")

# También puedes acceder a los píxeles de la imagen
#pixeles = list(imagen.getdata())
#print(f"Primer píxel: {pixeles[0]}")

# Cierra la imagen
#imagen.close()

In [30]:
import os
from PIL import Image
# Ruta a la carpeta raíz que contiene las subcarpetas con las imágenes PGM
ruta_raiz = '/content/drive/Shareddrives/FdeAnaliticaG4/Proyecto3/faces_4'


rutas_imagenes = []

# Recorre las subcarpetas y busca las imágenes PGM
for directorio_raiz, directorios, archivos in os.walk(ruta_raiz):
    for archivo in archivos:
        if archivo.lower().endswith('.pgm'):
            # Construye la ruta completa al archivo
            ruta_completa = os.path.join(directorio_raiz, archivo)
            rutas_imagenes.append(ruta_completa)
# Ahora tienes todas las rutas de las imágenes PGM en la lista rutas_imagenes
# Puedes cargar las imágenes si es necesario
imagenes = [cv2.imread(ruta) for ruta in rutas_imagenes]

# Para verificar la cantidad de imágenes
print(f'Se encontraron {len(imagenes)} imágenes PGM.')

# Para acceder a una imagen específica
imagen_1 = imagenes[0]

Se encontraron 624 imágenes PGM.


In [31]:
# Ruta en tu Google Drive donde guardar el archivo
ruta_archivo = '/content/drive/Shareddrives/FdeAnaliticaG4/Proyecto3/imagenes.pkl'

with open(ruta_archivo, 'wb') as archivo:
    pickle.dump(imagenes, archivo)

In [32]:
ruta_archivo = '/content/drive/Shareddrives/FdeAnaliticaG4/Proyecto3/imagenes.pkl'

with open(ruta_archivo, 'rb') as archivo:
    import_img = pickle.load(archivo)
print(f'Se encontraron {len(import_img)} imágenes PGM.')

Se encontraron 624 imágenes PGM.


In [33]:
# Convirtamos las imágenes en vectores y luego construimos una matriz
# con estos vectores como filas
img_vectorizadas = [i.flatten() for i in import_img]
imagenes_matriz = np.vstack(img_vectorizadas)
imagenes_matriz = imagenes_matriz-imagenes_matriz.mean()
print(imagenes_matriz.shape)

(624, 2880)


In [34]:
# Calculemos la matriz de correlación:
S = np.corrcoef(imagenes_matriz.T)
print(S.shape)

(2880, 2880)


In [35]:
for elemento in import_img:
    tipo = type(elemento)
    print(f"Elemento: {elemento}, Tipo: {tipo}")

Se han truncado las últimas 5000 líneas del flujo de salida.
  [37 37 37]
  [35 35 35]]], Tipo: <class 'numpy.ndarray'>
Elemento: [[[ 5  5  5]
  [18 18 18]
  [22 22 22]
  ...
  [20 20 20]
  [20 20 20]
  [20 20 20]]

 [[ 9  9  9]
  [15 15 15]
  [19 19 19]
  ...
  [21 21 21]
  [20 20 20]
  [21 21 21]]

 [[26 26 26]
  [17 17 17]
  [12 12 12]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 4  4  4]
  ...
  [38 38 38]
  [37 37 37]
  [34 34 34]]

 [[ 0  0  0]
  [ 0  0  0]
  [36 36 36]
  ...
  [59 59 59]
  [36 36 36]
  [34 34 34]]

 [[ 9  9  9]
  [10 10 10]
  [67 67 67]
  ...
  [97 97 97]
  [35 35 35]
  [33 33 33]]], Tipo: <class 'numpy.ndarray'>
Elemento: [[[ 5  5  5]
  [18 18 18]
  [22 22 22]
  ...
  [20 20 20]
  [20 20 20]
  [21 21 21]]

 [[ 9  9  9]
  [15 15 15]
  [19 19 19]
  ...
  [21 21 21]
  [20 20 20]
  [20 20 20]]

 [[25 25 25]
  [16 16 16]
  [12 12 12]
  ...
  [21 21 21]
  [20 20 20]
  [21 21 21]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 5  5  5]
  ..